# Generated by Django 4.0.3 on 2022-04-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_category_item_description_item_discount_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
