# Generated by Django 4.0.3 on 2022-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_blogpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='order_item',
            field=models.ManyToManyField(to='main.order'),
        ),
    ]
