# Generated by Django 4.0.3 on 2022-04-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_billingaddress_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='order_item',
        ),
    ]
