# Generated by Django 4.0.3 on 2022-05-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_billingaddress_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='payment_option',
            field=models.CharField(choices=[('C', 'CashOnDelevery')], default=None, max_length=2),
        ),
    ]
